# Permalinks
permalink:        pretty

#Removed this parameter in order to work in Jekyll 3
#relative_permalinks: true

# Setup
title:            Raúl Ávila
tagline:          Blog
url:              http://www.raulavila.com
paginate:         5
baseurl:          /
author:
  name:           Raul Avila
  url:            https://twitter.com/ravila80
  email:          ravila80@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/raulavila/raulavila.github.io

# Build
exclude: [Rakefile]

# Gems
gems: [jekyll-paginate]
